-- MySQL Script generated by MySQL Workbench
-- Thu Dec  4 12:01:41 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`labratorio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`labratorio` ;

CREATE TABLE IF NOT EXISTS `mydb`.`labratorio` (
  `idlabratorio` INT NOT NULL,
  `nome_laboratorio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idlabratorio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`marca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`marca` ;

CREATE TABLE IF NOT EXISTS `mydb`.`marca` (
  `idmarca` INT NOT NULL,
  `nome_marca` VARCHAR(45) NOT NULL,
  `idlaboratorio` INT NOT NULL,
  PRIMARY KEY (`idmarca`),
  INDEX `idlaboratorio_idx` (`idlaboratorio` ASC),
  CONSTRAINT `idlaboratorio`
    FOREIGN KEY (`idlaboratorio`)
    REFERENCES `mydb`.`labratorio` (`idlabratorio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`medicamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`medicamento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`medicamento` (
  `idmedicamento` INT NOT NULL,
  `nome_medicamento` VARCHAR(45) NOT NULL,
  `preco` INT NOT NULL,
  `quantidade` INT NOT NULL,
  `avaliacao` VARCHAR(45) NULL,
  `idmarca` INT NOT NULL,
  PRIMARY KEY (`idmedicamento`),
  INDEX `idmarca_idx` (`idmarca` ASC),
  CONSTRAINT `idmarca`
    FOREIGN KEY (`idmarca`)
    REFERENCES `mydb`.`marca` (`idmarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sintoma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`sintoma` ;

CREATE TABLE IF NOT EXISTS `mydb`.`sintoma` (
  `idsintoma` INT NOT NULL,
  `nome_sintoma` VARCHAR(90) NOT NULL,
  PRIMARY KEY (`idsintoma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`farmaco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`farmaco` ;

CREATE TABLE IF NOT EXISTS `mydb`.`farmaco` (
  `idfarmaco` INT NOT NULL,
  `nome_farmaco` VARCHAR(90) NOT NULL,
  `subgrupo_anvisa` VARCHAR(90) NOT NULL,
  PRIMARY KEY (`idfarmaco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`sintoma_farmaco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`sintoma_farmaco` ;

CREATE TABLE IF NOT EXISTS `mydb`.`sintoma_farmaco` (
  `idsintoma` INT NOT NULL,
  `idfarmaco` INT NOT NULL,
  INDEX `idsintoma_idx` (`idsintoma` ASC),
  INDEX `idfarmaco_idx` (`idfarmaco` ASC),
  CONSTRAINT `idsintoma`
    FOREIGN KEY (`idsintoma`)
    REFERENCES `mydb`.`sintoma` (`idsintoma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idfarmaco`
    FOREIGN KEY (`idfarmaco`)
    REFERENCES `mydb`.`farmaco` (`idfarmaco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`farmaco_medicamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`farmaco_medicamento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`farmaco_medicamento` (
  `idmedicamento` INT NOT NULL,
  `idfarmaco` INT NOT NULL,
  INDEX `idmedicamento_idx` (`idmedicamento` ASC),
  INDEX `idfarmaco_idx` (`idfarmaco` ASC),
  CONSTRAINT `idmedicamento`
    FOREIGN KEY (`idmedicamento`)
    REFERENCES `mydb`.`medicamento` (`idmedicamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idfarmaco`
    FOREIGN KEY (`idfarmaco`)
    REFERENCES `mydb`.`farmaco` (`idfarmaco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `idusuario` INT NOT NULL,
  `nome_usuario` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `genero` VARCHAR(15) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ficha`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ficha` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ficha` (
  `idficha` INT NOT NULL,
  `idusuario` INT NOT NULL,
  `peso` FLOAT NOT NULL,
  `altura` FLOAT NOT NULL,
  `data_ficha` DATETIME NOT NULL,
  PRIMARY KEY (`idficha`),
  INDEX `idusuario_idx` (`idusuario` ASC),
  CONSTRAINT `idusuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `mydb`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ficha_sintoma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ficha_sintoma` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ficha_sintoma` (
  `idficha` INT NOT NULL,
  `idsintoma` INT NOT NULL,
  INDEX `idficha_idx` (`idficha` ASC),
  INDEX `idsintoma_idx` (`idsintoma` ASC),
  CONSTRAINT `idficha`
    FOREIGN KEY (`idficha`)
    REFERENCES `mydb`.`ficha` (`idficha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idsintoma`
    FOREIGN KEY (`idsintoma`)
    REFERENCES `mydb`.`sintoma` (`idsintoma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`modelo_recomendado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`modelo_recomendado` ;

CREATE TABLE IF NOT EXISTS `mydb`.`modelo_recomendado` (
  `idmodelo` INT NOT NULL,
  `nome_algoritmo` VARCHAR(45) NOT NULL,
  `metricas` JSON NOT NULL,
  PRIMARY KEY (`idmodelo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`recomendacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`recomendacao` ;

CREATE TABLE IF NOT EXISTS `mydb`.`recomendacao` (
  `idrecomendacao` INT NOT NULL,
  `idficha` INT NOT NULL,
  `idmedicamento` INT NOT NULL,
  `idmodelo` INT NOT NULL,
  `data` DATE NULL,
  PRIMARY KEY (`idrecomendacao`),
  INDEX `idmodelo_idx` (`idmodelo` ASC),
  INDEX `idficha_idx` (`idficha` ASC),
  INDEX `idmedicamento_idx` (`idmedicamento` ASC),
  CONSTRAINT `idmodelo`
    FOREIGN KEY (`idmodelo`)
    REFERENCES `mydb`.`modelo_recomendado` (`idmodelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idficha`
    FOREIGN KEY (`idficha`)
    REFERENCES `mydb`.`ficha` (`idficha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idmedicamento`
    FOREIGN KEY (`idmedicamento`)
    REFERENCES `mydb`.`medicamento` (`idmedicamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
